### PR TITLE
[#164] build: example BODS_INDEX using wildcard

### PR DESCRIPTION
**Pull request by tiredpixel**
This is as explained in https://github.com/openownership/register/issues/164 . The result of a follow-on discussion was that changing `BODS_INDEX` for register-v2 to contain a wildcard should be safe, because it only uses the Elasticsearch indexes read-only.

A brief review was conducted to give some confidence about this. The main Elasticsearch-related calls made by register-v2 are:

- `EntityService` `find_by_entity_id`
- `EntityService` `search`
- `EntityService` `find`
- `EntityService` `count_legal_entities`
- `EntityService` `fallback_search`

All of these appear to be safe to use with a wildcard within the Elasticsearch index name.

A brief review from the direction of the libraries was conducted. The main unsafe Elasticsearch-related calls appear to be:

- `RegisterSourcesBods::Repositories::BodsStatementRepository` `store`
- `RegisterSourcesBods::Services::EsIndexCreator` `create_es_index`

However, these do not appear to be used in register-v2.

Setting `BODS_INDEX` to `bods_v2_psc_prod2` searches only the PSC Elasticsearch index. Setting it to `bods_v2_*_prod2`, however, searches all matching datasources; i.e. DK, PSC, SK.

Note that currently, there are no non-PSC datasources for `bods_v2_*_prod2`, only for `bods_v2_*_prod100`. These or alternatives need to be generated before this will yield anything interesting.

Setting `BODS_INDEX` to `bods_v2_*_prod100` results in extra rows being shown from the SK or DK datasources.

However, searching for `tesco stores` and clicking on an SK row errors:

```txt
register-v2-web-1  | Started GET "/entities/16040802136110075669" for 192.168.124.1 at 2023-07-04 14:33:17 +0000
register-v2-web-1  | Cannot render console from 192.168.124.1! Allowed networks: 10.0.2.2, 127.0.0.0/127.255.255.255, ::1
register-v2-web-1  | Processing by EntitiesController#show as HTML
register-v2-web-1  |   Parameters: {"id"=>"16040802136110075669"}
register-v2-web-1  | Completed 500 Internal Server Error in 2217ms (Allocations: 46234)
register-v2-web-1  | 
register-v2-web-1  | 
register-v2-web-1  |   
register-v2-web-1  | NoMethodError (undefined method `data' for nil:NilClass
register-v2-web-1  | 
register-v2-web-1  |       @newest_raw_record = RAW_DATA_RECORD_REPOSITORY.newest_for_entity(entity).data.notified_on # .updated_at
register-v2-web-1  |                                                                                ^^^^^):
register-v2-web-1  |   
register-v2-web-1  | app/controllers/entities_controller.rb:81:in `show'
```

I don't know if this is related to datasources, or something else. Do we think that something needs extending to support this, or is it unrelated? Some PSC rows errored, too, but differently, so I'm not sure if they're related.

### CODE REVIEW

**Comment by StephenAbbott** [comment]
Will leave this open for @spacesnottabs to comment on why we might be seeing a few SK and UK errors

**Comment by spacesnottabs** [comment]
This error is unrelated and is due to the task "Support raw records lookup for DK and SK sources #162" not having been completed yet. Looks good to me

**Comment by tiredpixel** [comment]
Thanks, @spacesnottabs . In that case, are you and @StephenAbbott happy to merge this? Then we can discuss when to update the Heroku config to make the update live for register-v2 stg.

**Review by spacesnottabs — APPROVED** [review]

**Comment by tiredpixel** [comment]
@spacesnottabs has updated the Heroku config—thanks for that. I've double-checked that and the expected search behaviour. So we can merge this.

**Pull request merged**
